### ISSUE TITLE
Broke after last sublime update

### ISSUE THREAD

**Issue by roman-kirsanov** [jaychsu/sublime-polymer-highlight#1]
Using polymer-syntax plugin for my framework, it looks like this:
<img width="949" alt="screen shot 2018-05-11 at 14 16 39" src="https://user-images.githubusercontent.com/3323864/39923728-86e836e8-552d-11e8-8eab-99e521f923c1.png">
or
<img width="692" alt="screen shot 2018-05-11 at 15 13 49" src="https://user-images.githubusercontent.com/3323864/39923839-f975a84e-552d-11e8-8ffa-d4e014832e9a.png">
And as you can see double curly braces are broken.

Here is my settings for syntax:
```
%YAML 1.2
---
# See http://www.sublimetext.com/docs/3/syntax.html
name: JavaScript RSX
file_extensions:
  - js
scope: source.js.rsx
contexts:
  main:
    - match: ""
      push: scope:source.js
      with_prototype:
      - match: 'styles: `'
        push:
          - meta_content_scope: source.css.embedded.html
          - include: scope:source.css
          - match: '`'
            pop: true
      - match: 'template: `'
        push:
          - meta_content_scope: text.html.basic.embedded.js
          - include: scope:text.html.basic
          - match: '@@\w+|@\w+'
            scope: entity.name.tag.block.any.html
          - match: '`'
            pop: true
```

could you please point me where I can fix it in my sublime settings etc.

Thnaks!
